#!/bin/env python3

import os
import copy
import sys
import json
import pygit2
import argparse
from pygit2 import GIT_MERGE_ANALYSIS_FASTFORWARD, GIT_MERGE_ANALYSIS_NORMAL, GIT_MERGE_ANALYSIS_UP_TO_DATE

# Exit status codes
GMUX_SUCCESS = 0
GMUX_FAILURE = 0


# HOTFIX: cuz args.taskids is for help command and task IDs.
# Gmux() sets current task ID by default, but it is wrong value when command
# 'help' is invoked.
COMMAND = None

"""
TODO:
"""

pgname = "tec-gmux"
default_cmd = "show"


helpmsg = {
    'remove': {
        'tag' : "basic",
        'synop': "Usage: tec gmux rm [OPTION]... [ID]...",
        'desc_short': "Remove gmux unit values.",
        'desc_long':
        """
     Options:
       -h        show help message and exit
       -v        verbose mode

     Arguments:
       ID        Task ID, if not passed then current task ID is used

     Exit status:
       Under development
        """,
    },
    'rsync': {
        'tag' : "basic",
        'synop': "Usage: tec gmux rsync [OPTION]...",
        'desc_short': "Update task branch with remote",
        'desc_long':
        """
     Options:
       -h        show help message and exit
       -r        rebase branch against default branch
       -v        verbose mode

     Arguments:
       ID        Task ID, if not passed then current task ID is used

     Exit status:
       Under development
       """,
    },
    'show': {
        'tag' : "basic",
        'synop': "Usage: tec gmux show [OPTION]... [ID]...",
        'desc_short': "Show gmux unit values.",
        'desc_long':
        """
     Options:
       -h        show help message and exit
       -v        verbose mode

     Arguments:
       ID        Task ID, if not passed then current task ID is used

     Exit status:
       Under development
        """,
    },
    'sync': {
        'tag' : "basic",
        'synop': "Usage: tec gmux sync [OPTION]...",
        'desc_short': "Update task branch",
        'desc_long':
        """
     Options:
       -h        show help message and exit
       -r        rebase branch against default branch
       -v        verbose mode

     Arguments:
       ID        Task ID, if not passed then current task ID is used

     Exit status:
       Under development
       """,
    },
}

def merge(repo, remote_name='origin', branch='master'):
    """
    Performs a git pull equivalent: fetches the remote and updates the local branch.

    Args:
        repo: pygit2.Repository instance
        remote_name: Name of the remote (e.g., 'origin')
        branch: Name of the branch to pull (e.g., 'master')
    """

    # 1. Get the remote tracking branch reference
    remote_branch_name = f'refs/remotes/{remote_name}/{branch}'
    remote_commit_id = repo.lookup_reference(remote_branch_name).target
    remote_commit = repo.get(remote_commit_id)

    # 2. Analyze if and how we can merge
    merge_result, _ = repo.merge_analysis(remote_commit_id)

    # 3. Case 1: Already up to date
    if merge_result & GIT_MERGE_ANALYSIS_UP_TO_DATE:
        #print("Already up to date.")
        return

    # 4. Case 2: Fast-forward possible
    elif merge_result & GIT_MERGE_ANALYSIS_FASTFORWARD:
        print("Fast-forwarding...")
        # Move the branch reference and HEAD to the remote commit
        repo.checkout_tree(remote_commit)
        branch_ref = repo.lookup_reference(f'refs/heads/{branch}')
        branch_ref.set_target(remote_commit_id)
        repo.head.set_target(remote_commit_id)
        #print(f"Updated to {remote_commit_id.hex}")

    # 5. Case 3: True merge required
    elif merge_result & GIT_MERGE_ANALYSIS_NORMAL:
        print("Merging...")
        # Perform the merge
        repo.merge(remote_commit_id)

        # Check for conflicts
        if repo.index.conflicts:
            print("Conflicts detected! Please resolve them manually.")
            # You can iterate through conflicts if needed:
            # for conflict in repo.index.conflicts:
            #     print(f"Conflict in: {conflict[0].path}")
            return

        # No conflicts: commit the merge
        user = repo.default_signature
        tree = repo.index.write_tree()
        repo.create_commit(
            'HEAD',
            user,
            user,
            f"Merge remote branch '{remote_name}/{branch}'",
            tree,
            [repo.head.target, remote_commit_id]
        )
        # Clean up merge state
        repo.state_cleanup()
        print("Merge completed successfully.")

    else:
        raise RuntimeError("Unknown merge analysis result")


class Log:
    def __init__(self):
        pass

    def err(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg, file=sys.stderr)
        return 1

    def info(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg)
        return 0

    def debug(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg)
        return 0

class Branch(Log):
    def __init__(self, pattern):
        self.branch = None
        self.pattern = pattern
        self.branch_stored = None

    def generate(self, units, prefix, tasktype):
        delimiters = r'[/_-]+'
        pattern = copy.deepcopy(self.pattern)

        for obj in units:
            #print("## obj", obj, "-", units[obj].upper())
            pattern = pattern.replace(obj.upper(), units[obj])

        # TODO: hotfix - replace whitespaces with underscore in description
        pattern = pattern.replace(" ", "_")

        # HOTFIX: replace prefix as well
        pattern = pattern.replace("PREFIX", prefix)
        # HOTFIX: replace task type as well
        pattern = pattern.replace("TYPE", tasktype)

        #print("--> new pattern", pattern)
        return pattern # i.e. newly generated branch

    def get(self):
        return self.branch

class Repo(Log):
    def __init__(self, config, path):
        self.log = Log()
        self.config = config
        self.path = path + "/.tec/pgn/gmux/"

        self.clone()

    def clone(self):
        for cfg in self.config['repos']:
            repodir = "/".join([self.path + cfg['name']])
            if not os.path.exists(repodir):
                repo = pygit2.clone_repository(cfg['link'], repodir)
            else:
                repo = pygit2.Repository(repodir)

            for submodule in repo.submodules:
                submodule.init()
                submodule.update(init=True)
        return True

    def symlink(self, cfg, dst, taskid):
        dst = "/".join([dst, taskid])
        repo_src = self.path + cfg['name']
        repo_dst = "/".join([dst, cfg['name']])
        if not os.path.exists(repo_src):
            self.log.err("repo not cloned yet")
        elif not os.path.islink(repo_dst):
            os.symlink(repo_src, repo_dst)

    def has_uncommited_changes(self, cfg):
        repo = pygit2.Repository(self.path + cfg['name'])
        status = repo.status()
        return len(status) > 0

    def fetch(self, cfg, remote_name="origin"):
        repo = pygit2.Repository(self.path + cfg['name'])
        self.log.info("fetching repo '%s'", cfg["name"])
        remote = repo.remotes[remote_name]
        remote.fetch()
        return True

    def merge(self, cfg, remote_name="origin"):
        repo = pygit2.Repository(self.path + cfg['name'])
        self.log.info("'%s': merge repo", cfg['name'])
        merge(repo, 'origin', cfg['branch'])
        return True

    # Get default branch name from remote
    def branch_get_default(self, repo):
        remote_head = repo.references.get("refs/remotes/origin/HEAD")
        if remote_head:
            default_branch = remote_head.resolve().shorthand.replace('origin/', '')
            return default_branch
        return None

    # TODO: find a way to join this function and branch_switch()
    def branch_switch_default(self, cfg):
        status = True
        reponame = cfg['name']
        branch = cfg['branch']

        # TODO: switch branch in submodules as well
        # TODO: let not nonexisting brach to break the loop
        try:
            branch_name = branch
            repo = pygit2.Repository(self.path + reponame)

            # TODO: check that repo has no uncommited changes
            if branch_name not in repo.branches:
                self.log.err("'%s': no such default branch in repo '%s'", branch_name, reponame)
            elif branch_name == repo.head.shorthand:
                self.log.info("already on default branch '%s'", reponame)
            else:
                repo.checkout(repo.branches[branch_name])
        except pygit2.GitError as e:
            self.log.err("git error: %s", reponame)
            status = False
        return status

    def branch_switch(self, cfg, branch_name):
        reponame = cfg['name']
        branch = cfg['branch']
        # TODO: switch branch in submodules as well
        # TODO: let not nonexisting brach to break the loop
        try:
            repo = pygit2.Repository(self.path + reponame)

            # TODO: check that repo has no uncommited changes
            if cfg["branch"] not in repo.branches:
                self.log.err("'%s': no such base branch in repo '%s'", branch, reponame)
            elif branch_name not in repo.branches:
                self.log.err("'%s': no such task branch in repo '%s'", branch, reponame)
            elif cfg["name"] == repo.head.shorthand:
                self.log.info("already on base branch '%s'", reponame)
            else:
                repo.checkout(repo.branches[branch_name])
        except pygit2.GitError as e:
            self.err("git error")
        return True

    def branch_remove(self, cfg, branch_name):
        repo = pygit2.Repository(self.path + cfg['name'])
        if branch_name in repo.branches:
            if self._has_uncommited_changes(cfg['name']) == False:
                repo.checkout(repo.branches[cfg['branch']])
                repo.branches.delete(branch_name)
            else:
                self.log.err("%s: repo has uncommited changes", cfg['name'])


    def branch_update(self, cfg, oldbranch, newbranch):
        reponame = cfg['name']
        branch = cfg['branch']

        if oldbranch == newbranch:
            if self._has_uncommited_changes(reponame) == True:
                self.log.err(f"{reponame}: has uncommited changes")
                return False
            elif self._branch_exist(reponame, oldbranch) == False:
                self._branch_create(reponame, oldbranch, branch)
        elif oldbranch is not None:
            self._branch_rename(reponame, oldbranch, newbranch)
        elif self._branch_exist(reponame, newbranch) == False:
            self._branch_create(reponame, newbranch, branch)

    def _has_uncommited_changes(self, reponame):
        repo = pygit2.Repository(self.path + reponame)
        for cfg in self.config['repos']:
            status = repo.status()
            if cfg['name'] == reponame and bool(status) == True:
                return True
        return False

    def _branch_exist(self, reponame, branchname):
        repo = pygit2.Repository(self.path + reponame)
        for cfg in self.config['repos']:
            if cfg['name'] == reponame and branchname in repo.branches:
                return True
        return False

    def _branch_create(self, reponame, new_branch_name, src_branch_name):
        repo = pygit2.Repository(self.path + reponame)
        for cfg in self.config['repos']:
            if cfg['name'] == reponame:
                src_branch = repo.branches[src_branch_name]
                new_branch = repo.branches.local.create(new_branch_name, repo[src_branch.target])
                return True
        return False

    def _branch_rename(self, reponame, old_branch, new_branch):
        repo = pygit2.Repository(self.path + reponame)
        for cfg in self.config['repos']:
            if cfg['name'] == reponame:
                branch = repo.branches.local[old_branch]
                branch.rename(new_branch)
                return True
        return False

class Config(Log):
    def __init__(self):
        self.config = None
        fname = self._get_config_file()

        if fname == None:
            self.err("no config file is found")
            sys.exit(1)
        with open(fname) as file:
            self.config = json.load(file)

    def _get_defaults(self, cfg):
        cfg.setdefault("repos", [])
        cfg.setdefault("prefix", "gmux")
        cfg.setdefault("type", "feature")
        cfg.setdefault("branchpatt", "TYPE/PREFIX-ID_DESC_DATE")
        return cfg

    def _get_config_file(self):
        paths = [
            "/".join([os.environ["HOME"], ".tec/pgn/gmux.json"]),
            "/".join([os.environ["HOME"], ".config/tec/pgn/gmux.json"]),
        ]
        for cfg in paths:
            if os.path.exists(cfg):
                return cfg
        return None

    def get(self, env):
        cfg = {}
        for k, v in self.config.items():
            if k == env:
                cfg = v
        return self._get_defaults(cfg)


class Unit:
    def __init__(self, pathbase):
        self.units = {}
        self.unitpgn = {}
        self.pathbase = pathbase
        self._bin_suffix_path = ".tec/units"
        self._pgn_suffix_pathdir = ".tec/pgn"
        self._pgn_suffix_path = "/".join([self._pgn_suffix_pathdir, "gmux"])

    def make_dir(self, taskid):
        dirname = "/".join([self.pathbase, taskid, self._pgn_suffix_pathdir])
        if not os.path.exists(dirname):
            os.mkdir(dirname)

    def _get_units(self, path):
        units = {}

        with open(path) as file:
            lines = file.readlines()

        for line in lines:
            line = line.strip("\n")
            key, val = line.split(":")
            units.update({key.strip(" "): val.strip(" ")})
        return units

    def getall(self, taskid):
        filebin = "/".join([self.pathbase, taskid, self._bin_suffix_path])
        unitbin = self._get_units(filebin)
        self.unitpgn = self.get(taskid)
        return { 'id' : taskid, **unitbin, **self.unitpgn}

    def get(self, taskid):
        filepgn = "/".join([self.pathbase, taskid, self._pgn_suffix_path])
        if os.path.exists(filepgn):
            return self._get_units(filepgn)
        return {}

    def set(self, units):
        for key, val in units.items():
            self.unitpgn[key] = val

    def save(self, taskid):
        filepgn = "/".join([self.pathbase, taskid, self._pgn_suffix_path])
        with open(filepgn, 'w') as file:
            for key, val in self.unitpgn.items():
                file.write(f"{key}: {val}\n")

class TecArgs(Log):
    def __init__(self, taskbase):
        self.taskbase = taskbase
        self.env = None
        self.desk = None
        self.taskid = None
        self.path_suffix = ".tec/toggles"

    # TODO: handle case when toggle file is empty
    def _get_env(self, env):
        if env:
            self.env = env
            return True

        file = "/".join([self.taskbase, self.path_suffix])
        with open(file) as file:
            lines = file.readlines()

        # TODO: add a better parser cuz ' :' might not get parsed
        value = lines[0].strip().partition(' : ')[-1]
        self.env = value
        return True

    # TODO: handle case when toggle file is empty
    def _get_desk(self, env, desk):
        if desk:
            self.desk = desk
            return True

        fname = "/".join([self.taskbase, env, self.path_suffix])
        with open(fname) as file:
            lines = file.readlines()

        # TODO: add a better parser cuz ' :' might not get parsed
        value = lines[0].strip().partition(' : ')[-1]
        self.desk = value
        return True

    def get(self, env, desk):
        if self._get_env(env) is False:
            self.err("'%s': no current env", "CURR")
            return False
        elif self.env_exist() is False:
            self.err("'%s': no such env", self.env)
            return False
        elif self._get_desk(self.env, desk) is False:
            self.err("'%s': no current desk", self.desk)
            return False
        elif self.desk_exist() is False:
            self.err("'%s': no such desk", self.desk)
            return False

    # TODO: use class Unit()
    def get_curr_taskID(self):
        lines = []
        fname = "/".join([self.taskbase, self.env, self.desk, self.path_suffix])

        # Current task ID might not exist, and it is fine
        if os.path.exists(fname):
            with open(fname) as file:
                lines = file.readlines()

        if len(lines) > 0:
            # TODO: add a better parser cuz ' :' might not get parsed
            value = lines[0].strip().partition(' : ')[-1]
            self.taskid = value
            return value
        return None

    def env_exist(self):
        dir = "/".join([self.taskbase, self.env])
        return os.path.exists(dir)

    def desk_exist(self):
        dir = "/".join([self.taskbase, self.env, self.desk])
        return os.path.exists(dir)

    def task_exist(self, taskid):
        dir = "/".join([self.taskbase, self.env, self.desk, taskid])
        return os.path.exists(dir)

class Gmux(Repo):
    def __init__(self, taskbase, env, desk, taskids):
        self.log = Log()
        self.taskids = taskids
        self.taskbase = taskbase
        self.suffix_dir = ".tec/pgn"
        self.suffix_unit = self.suffix_dir + "/" + "gmux"
        self.args = TecArgs(self.taskbase)

        if self.args.get(env, desk) is False:
            sys.exit(1)

        global COMMAND
        if len(self.taskids) == 0 and COMMAND != 'help':
            if (taskid := self.args.get_curr_taskID()) is None:
                self.log.err("'%s': no current task ID", "CURR")
                sys.exit(1)
            self.taskids.append(taskid)
        # NOTE: args values need to be parsed first (it's done above)
        self.settings = Config().get(self.args.env)

    def _getpath(self):
        return "/".join([self.args.taskbase, self.args.env, self.args.desk])

    def commit(self):
        retcode = 1
        return retcode

    def remove(self):
        retcode = True
        dst = self._getpath()
        unit = Unit(dst)
        repo = Repo(self.settings, self.args.taskbase)

        # TODO: Execute the same for submodules if needed
        for taskid in self.taskids:
            if self.args.task_exist(taskid) is False:
                retcode = False
                self.log.err("'%s': no such task ID", taskid)
                continue

            units = unit.getall(taskid)
            branch_stored = units.get('branch')

            for cfg in self.settings['repos']:
                if repo.symlink(cfg, dst, taskid) is False:
                    retcode = False
                    self.log.err("'%s': could not create symlink", cfg['name'])
                elif repo.branch_remove(cfg, branch_stored) == False:
                    retcode = False
                    self.log.err("'%s': could not remove task branch", cfg['name'])
        return GMUX_SUCCESS if retcode == True else GMUX_FAILURE

    def help(self):
        retcode = 1
        cmds = self.taskids # these are commands not task IDs
        opts = {
                'synop' : True,
                'desc_short': True,
                'desc_long': True,
            }

        if len(cmds) == 0:
            for cmd in helpmsg:
                print(cmd, "\t", helpmsg[cmd]['desc_short'])
            return 0

        for cmd in cmds:
            _cmd = helpmsg.get(cmd)
            if _cmd is not None:
                print(_cmd['synop'])
                print("    ", _cmd['desc_short'])
                print("    ", _cmd['desc_long'])
                retcode = 0
            else:
                print(f"gmux: help: no such command '{cmd}'")
                retcode = 1
        return retcode

    def show(self):
        retcode = True
        unit = Unit(self._getpath())

        for taskid in self.taskids:
            if self.args.task_exist(taskid) is False:
                retcode = False
                self.log.err("'%s': no such task ID", taskid)
                continue

            units = unit.get(taskid)
            for key, value in units.items():
                print(f"{key} : {value}")
        return GMUX_SUCCESS if retcode == True else GMUX_FAILURE

    def sync(self):
        retcode = True
        dst = self._getpath()
        unit = Unit(dst)
        branch = Branch(self.settings['branchpatt'])
        repo = Repo(self.settings, self.args.taskbase)

        # TODO: Execute the same for submodules if needed
        for taskid in self.taskids:
            if self.args.task_exist(taskid) is False:
                retcode = False
                self.log.err("'%s': no such task ID", taskid)
                continue

            unit.make_dir(taskid)
            units = unit.getall(taskid)
            branch_stored = units.get('branch')
            branch_generated = branch.generate(units, self.settings['prefix'], self.settings['type'])

            for cfg in self.settings['repos']:
                if repo.symlink(cfg, dst, taskid) is False:
                    retcode = False
                    self.log.err("'%s': could not create symlink", cfg['name'])
                elif repo.has_uncommited_changes(cfg) == True:
                    retcode = False
                    self.log.err("'%s': repo has uncommited changes", cfg['name'])
                elif repo.branch_update(cfg, branch_stored, branch_generated) is False:
                    self.log.err("'%s': could not update branch", "<REPO>")
                    retcode = False
                elif repo.branch_switch(cfg, branch_generated) == False:
                    self.log.err("'%s': could not switch to task branch", cfg['name'])
                    retcode = False
                elif repo.merge(cfg) == False:
                    self.log.err("'%s': could not merge branch", cfg['name'])
                    retcode = False

            if retcode == True and branch_stored != branch_generated:
                unit.set({ 'branch' : branch_generated })
                unit.save(taskid)

        return GMUX_SUCCESS if retcode == True else GMUX_FAILURE

    def rsync(self):
        retcode = True
        dst = self._getpath()
        unit = Unit(dst)
        branch = Branch(self.settings['branchpatt'])
        repo = Repo(self.settings, self.args.taskbase)

        # TODO: Execute the same for submodules if needed
        for taskid in self.taskids:
            if self.args.task_exist(taskid) is False:
                retcode = False
                self.log.err("'%s': no such task ID", taskid)
                continue

            unit.make_dir(taskid)
            units = unit.getall(taskid)
            branch_generated = branch.generate(units, self.settings['prefix'], self.settings['type'])

            for cfg in self.settings['repos']:
                if repo.symlink(cfg, dst, taskid) is False:
                    retcode = False
                    self.log.err("'%s': could not create symlink", cfg['name'])
                elif repo.has_uncommited_changes(cfg) == True:
                    retcode = False
                    self.log.err("'%s': repo has uncommited changes", cfg['name'])
                elif repo.branch_switch_default(cfg) is False:
                    self.log.err("'%s': could not switch to default branch", cfg['name'])
                    retcode = False
                elif repo.fetch(cfg) == False:
                    self.log.err("'%s': could not fetch changes", cfg['name'])
                    retcode = False
                elif repo.merge(cfg) == False:
                    self.log.err("'%s': could not merge to default branch", cfg['name'])
                    retcode = False
                elif repo.branch_switch(cfg, branch_generated) == False:
                    self.log.err("'%s': could not switch to task branch", cfg['name'])
                    retcode = False
        return GMUX_SUCCESS if retcode == True else GMUX_FAILURE

    def issue(self):
        print("manage MRs")


def parse_args():
    global COMMAND

    parser = argparse.ArgumentParser(description="Git multiplexer")
    parser.add_argument("-e", "--env", help="environment name")
    parser.add_argument("-d", "--desk", help="desk name")
    parser.add_argument("-P", "--pgnbase", help="pgn directory base")
    parser.add_argument("-T", "--taskbase", help="task directory base")
    parser.add_argument("cmd", default=default_cmd, nargs='?', type=str, help="subcommand")
    parser.add_argument("taskids", type=str, nargs='*', help="task ID")
    args = parser.parse_args()

    # HOTFIX
    COMMAND = args.cmd
    return args

def main():
    log = Log()
    args = parse_args()
    gmux = Gmux(args.taskbase, args.env, args.desk, args.taskids)
    cmd = getattr(gmux, args.cmd, None)

    if cmd is not None:
        res = cmd()
    else:
        res = log.err(f"'{args.cmd}': no such command")
    return res

sys.exit(main())
