#!/bin/env python3

import os
import re
import sys
import json
import copy
import pygit2
import argparse

"""
TODO:
    1. What if there is a cloned directory of managed repo in task directory?
"""

pgname = "tec-gmux"
default_cmd = "show"

class Log:
    def __init__(self):
        pass

    def err(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg, file=sys.stderr)
        return 1

    def info(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg)
        return 0

    def debug(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg)
        return 0

class Branch(Log):
    def __init__(self, pattern):
        self.branch = None
        self.pattern = pattern
        self.branch_stored = None

    def generate(self, units, prefix):
        delimiters = r'[/_-]+'
        pattern = copy.deepcopy(self.pattern)

        for obj in units:
            #print("## obj", obj, "-", units[obj].upper())
            pattern = pattern.replace(obj.upper(), units[obj])

        # TODO: hotfix - replace whitespaces with underscore in description
        pattern = pattern.replace(" ", "_")

        # HOTFIX: replace prefix as well
        pattern = pattern.replace("PREFIX", prefix)

        #print("--> new pattern", pattern)
        return pattern # i.e. newly generated branch

    def get(self):
        return self.branch

class Repo(Log):
    def __init__(self, config, path):
        self.log = Log()
        self.config = config
        self.path = path + "/.tec/pgn/gmux/"

        self.clone()

    def clone(self):
        # TODO: make sure submodules get cloned as well
        for _repo in self.config['repos']:
            repodir = self.path + _repo['name']
            if not os.path.exists(repodir):
                pygit2.clone_repository(_repo['link'], repodir)
        return True

    def symlink(self, dst, taskid):
        dst = "/".join([dst, taskid])
        for _repo in self.config['repos']:
            repo_src = self.path + _repo['name']
            repo_dst = "/".join([dst, _repo['name']])
            if not os.path.exists(repo_src):
                self.log.err("repo not cloned yet")
            elif not os.path.islink(repo_dst):
                os.symlink(repo_src, repo_dst)

    def branch_switch(self, branch_name):
        # TODO: switch branch in submodules as well
        # TODO: let not nonexisting brach to break the loop
        for _repo in self.config['repos']:
            try:
                repo = pygit2.Repository(self.path + _repo['name'])

                # TODO: check that repo has no uncommited changes
                if _repo["branch"] not in repo.branches:
                    self.log.err("'%s': no such base branch in repo '%s'", _repo["branch"], _repo["name"])
                elif branch_name not in repo.branches:
                    self.log.err("'%s': no such task branch in repo '%s'", _repo["branch"], _repo["name"])
                elif _repo["name"] == repo.head.shorthand:
                    self.log.info("already on base branch '%s'", _repo["name"])
                else:
                    repo.checkout(repo.branches[branch_name])
            except pygit2.GitError as e:
                self.err("git error")
        return True

    def branch_remove(self, branch_name):
        for _repo in self.config['repos']:
            repo = pygit2.Repository(self.path + _repo['name'])
            if branch_name in repo.branches:
                if self._has_uncommited_changes(_repo['name']) == False:
                    repo.checkout(repo.branches[_repo['branch']])
                    repo.branches.delete(branch_name)
                else:
                    self.log.err("%s: repo has uncommited changes", _repo['name'])

    # repo.branch_update(branch_stored, branch_generated)
    def branch_update(self, oldbranch, newbranch):
        for _repo in self.config['repos']:
            if oldbranch == newbranch:
                if self._has_uncommited_changes(_repo['name']) == True:
                    self.log.err(f"repo {_repo['name']} has uncommited changes")
                elif self._branch_exist(_repo['name'], oldbranch) == False:
                    self._branch_create(_repo['name'], oldbranch, _repo['branch'])
            elif oldbranch is not None:
                self._branch_rename(_repo['name'], oldbranch, newbranch)
            elif self._branch_exist(_repo['name'], newbranch) == False:
                self._branch_create(_repo['name'], newbranch, _repo['branch'])

    def branch_pull(self, branch_name, origin):
        if origin == None:
            origin = "origin"
        for _repo in self.config['repos']:
            repo = pygit2.Repository(self.path + _repo['name'])
            if self._has_uncommited_changes(_repo['name']) == True:
                self.err("'%s' has uncommited changes")
                continue
            repo.checkout(repo.branches[branch_name])


    def _has_uncommited_changes(self, reponame):
        repo = pygit2.Repository(self.path + reponame)
        for _repo in self.config['repos']:
            status = repo.status()
            if _repo['name'] == reponame and bool(status) == True:
                return True
        return False

    def _branch_exist(self, reponame, branchname):
        repo = pygit2.Repository(self.path + reponame)
        for _repo in self.config['repos']:
            if _repo['name'] == reponame and branchname in repo.branches:
                return True
        return False

    def _branch_create(self, reponame, new_branch_name, src_branch_name):
        repo = pygit2.Repository(self.path + reponame)
        for _repo in self.config['repos']:
            if _repo['name'] == reponame:
                src_branch = repo.branches[src_branch_name]
                new_branch = repo.branches.local.create(new_branch_name, repo[src_branch.target])
                return True
        return False

    def _branch_rename(self, reponame, old_branch, new_branch):
        repo = pygit2.Repository(self.path + reponame)
        for _repo in self.config['repos']:
            if _repo['name'] == reponame:
                branch = repo.branches.local[old_branch]
                branch.rename(new_branch)
                return True
        return False

class Config(Log):
    def __init__(self):
        self.config = None
        fname = self._get_config_file()

        if fname == None:
            self.err("no config file is found")
            sys.exit(1)
        with open(fname) as file:
            self.config = json.load(file)

    def _get_defaults(self, cfg):
        cfg.setdefault("prefix", "gmux")
        cfg.setdefault("branchpatt", "TYPE/PREFIX-ID_DESC_DATE")
        cfg.setdefault("repos", [])
        return cfg

    def _get_config_file(self):
        paths = [
            "/".join([os.environ["HOME"], ".tec/pgn/gmux.json"]),
            "/".join([os.environ["HOME"], ".config/tec/pgn/gmux.json"]),
        ]
        for cfg in paths:
            if os.path.exists(cfg):
                return cfg
        return None

    def get(self, env):
        cfg = {}
        for k, v in self.config.items():
            if k == env:
                cfg = v
        return self._get_defaults(cfg)


class Unit:
    def __init__(self, pathbase):
        self.units = {}
        self.unitpgn = {}
        self.pathbase = pathbase
        self._bin_suffix_path = ".tec/units"
        self._pgn_suffix_pathdir = ".tec/pgn"
        self._pgn_suffix_path = "/".join([self._pgn_suffix_pathdir, "gmux"])

    def make_dir(self, taskid):
        dirname = "/".join([self.pathbase, taskid, self._pgn_suffix_pathdir])
        if not os.path.exists(dirname):
            os.mkdir(dirname)

    def _get_units(self, path):
        units = {}

        with open(path) as file:
            lines = file.readlines()

        for line in lines:
            line = line.strip("\n")
            key, val = line.split(":")
            units.update({key.strip(" "): val.strip(" ")})
        return units

    def getall(self, taskid):
        filebin = "/".join([self.pathbase, taskid, self._bin_suffix_path])
        unitbin = self._get_units(filebin)
        self.unitpgn = self.get(taskid)
        return { 'id' : taskid, **unitbin, **self.unitpgn}

    def get(self, taskid):
        filepgn = "/".join([self.pathbase, taskid, self._pgn_suffix_path])
        if os.path.exists(filepgn):
            return self._get_units(filepgn)
        return {}

    def set(self, units):
        for key, val in units.items():
            self.unitpgn[key] = val

    def save(self, taskid):
        filepgn = "/".join([self.pathbase, taskid, self._pgn_suffix_path])
        with open(filepgn, 'w') as file:
            for key, val in self.unitpgn.items():
                file.write(f"{key}: {val}\n")

class TecArgs(Log):
    def __init__(self, taskbase):
        self.taskbase = taskbase
        self.env = None
        self.desk = None
        self.taskid = None
        self.path_suffix = ".tec/toggles"

    # TODO: handle case when toggle file is empty
    def _get_env(self, env):
        if env:
            self.env = env
            return True

        file = "/".join([self.taskbase, self.path_suffix])
        with open(file) as file:
            lines = file.readlines()

        # TODO: add a better parser cuz ' :' might not get parsed
        value = lines[0].strip().partition(' : ')[-1]
        self.env = value
        return True

    # TODO: handle case when toggle file is empty
    def _get_desk(self, env, desk):
        if desk:
            self.desk = desk
            return True

        fname = "/".join([self.taskbase, env, self.path_suffix])
        with open(fname) as file:
            lines = file.readlines()

        # TODO: add a better parser cuz ' :' might not get parsed
        value = lines[0].strip().partition(' : ')[-1]
        self.desk = value
        return True

    def get(self, env, desk):
        if self._get_env(env) is False:
            self.err("'%s': no current env", "CURR")
            return False
        elif self.env_exist() is False:
            self.err("'%s': no such env", self.env)
            return False
        elif self._get_desk(self.env, desk) is False:
            self.err("'%s': no current desk", self.desk)
            return False
        elif self.desk_exist() is False:
            self.err("'%s': no such desk", self.desk)
            return False

    # TODO: use class Unit()
    def get_curr_taskID(self):
        fname = "/".join([self.taskbase, self.env, self.desk, ".tec/toggles"])
        with open(fname) as file:
            lines = file.readlines()

        if len(lines) > 0:
            # TODO: add a better parser cuz ' :' might not get parsed
            value = lines[0].strip().partition(' : ')[-1]
            self.taskid = value
            return value
        return None

    def env_exist(self):
        dir = "/".join([self.taskbase, self.env])
        return os.path.exists(dir)

    def desk_exist(self):
        dir = "/".join([self.taskbase, self.env, self.desk])
        return os.path.exists(dir)

    def task_exist(self, taskid):
        dir = "/".join([self.taskbase, self.env, self.desk, taskid])
        return os.path.exists(dir)

class Gmux(Repo):
    def __init__(self, taskbase, env, desk, taskids):
        self.log = Log()
        self.taskids = taskids
        self.taskbase = taskbase
        self.suffix_dir = ".tec/pgn"
        self.suffix_unit = self.suffix_dir + "/" + "gmux"
        self.args = TecArgs(self.taskbase)

        if self.args.get(env, desk) is False:
            sys.exit(1)

        if len(self.taskids) == 0:
            if (taskid := self.args.get_curr_taskID()) is None:
                self.log.err("'%s': no current task ID", "CURR")
                sys.exit(1)
            self.taskids.append(taskid)
        # NOTE: args values need to be parsed first (it's done above)
        self.settings = Config().get(self.args.env)

    def _getpath(self):
        return "/".join([self.args.taskbase, self.args.env, self.args.desk])

    def commit(self):
        retcode = 1
        return retcode

    def remove(self):
        retcode = 0
        dst = self._getpath()
        unit = Unit(dst)
        branch = Branch(self.settings['branchpatt'])
        repo = Repo(self.settings, self.args.taskbase)

        # TODO: Execute the same for submodules if needed
        for taskid in self.taskids:
            if self.args.task_exist(taskid) is False:
                self.log.err("'%s': no such task ID", taskid)
                continue

            repo.symlink(dst, taskid)
            units = unit.getall(taskid)
            branch_stored = units.get('branch')
            branch_generated = branch.generate(units, self.settings['prefix'])

            repo.branch_remove(branch_generated)
        return retcode

    def help(self):
        retcode = 1
        for cmd in self.taskids: # these are commands not task IDs
            print(f"show help for command {cmd}")
            return 0
        print("show list of all commands")
        return retcode

    def merge(self):
        retcode = 1
        return retcode

    def revert(self):
        retcode = 1
        return retcode

    def show(self):
        retcode = 0
        unit = Unit(self._getpath())

        for taskid in self.taskids:
            units = unit.get(taskid)
            for key, value in units.items():
                print(f"{key} : {value}")
        return retcode

    def sync(self):
        retcode = 0
        dst = self._getpath()
        unit = Unit(dst)
        branch = Branch(self.settings['branchpatt'])
        repo = Repo(self.settings, self.args.taskbase)

        # TODO: Execute the same for submodules if needed
        for taskid in self.taskids:
            if self.args.task_exist(taskid) is False:
                self.log.err("'%s': no such task ID", taskid)
                continue

            unit.make_dir(taskid)
            repo.symlink(dst, taskid)
            units = unit.getall(taskid)
            branch_stored = units.get('branch')
            branch_generated = branch.generate(units, self.settings['prefix'])

            repo.branch_update(branch_stored, branch_generated)
            repo.branch_switch(branch_generated)

            if branch_stored != branch_generated:
                unit.set({ 'branch' : branch_generated })
                unit.save(taskid)
        return retcode

    def rsync(self):
        retcode = 0
        repo = Repo(self.settings, self.args.taskbase)

        self.err("under development")
        return 0

        # TODO: Execute the same for submodules if needed
        for taskid in self.taskids:
            if self.args.task_exist(taskid) is False:
                self.log.err("'%s': no such task ID", taskid)
                continue

            unit.make_dir(taskid)
            repo.symlink(dst, taskid)
            units = unit.getall(taskid)
            branch_name = units.get('branch')

            repo.branch_switch(self.settings['branch'])
            repo.branch_pull(self.settings['branch'])
        return retcode

parser = argparse.ArgumentParser(description="Git multiplexer")
parser.add_argument("-e", "--env", help="environment name")
parser.add_argument("-d", "--desk", help="desk name")
parser.add_argument("-P", "--pgnbase", help="pgn directory base")
parser.add_argument("-T", "--taskbase", help="task directory base")
parser.add_argument("cmd", default=default_cmd, nargs='?', type=str, help="subcommand")
parser.add_argument("taskids", type=str, nargs='*', help="task ID")
args = parser.parse_args()


def main():
    log = Log()
    gmux = Gmux(args.taskbase, args.env, args.desk, args.taskids)
    cmd = getattr(gmux, args.cmd, None)

    if cmd is not None:
        res = cmd()
    else:
        res = log.err(f"'{args.cmd}': no such command")
    sys.exit(res)

main()
